### ISSUE TITLE
user behavior driven testing ?

### ISSUE THREAD

**Issue by asmodehn** [asmodehn/pyros#122]
https://www.youtube.com/watch?v=ZEZBZFi_e88

**Comment by stonier** [comment]
Really, cucumber!? What is with these names!

**Comment by stonier** [comment]
Python people must hate life...they carry dieting extremes into their programming.

**Comment by asmodehn** [comment]
There is an implementation called lettuce as well... well if you want more
women into tech fields, some sacrifices need to be made :'/

**Comment by stonier** [comment]
Most women I know actually like chicken, ice cream, chocolate - if anything more than we do because of prolonged periods of enforced abstinence due to a society expecting them to look wonderful! So I suspect they _hate_ celery/cucumber/lettuce, but they may _hate more_ having to work with ice cream, chocolate and chicken while forbidden to partake of them :P

**Comment by asmodehn** [comment]
Since this package is moslty a python developer focused package, BDD doesn't seem suited for it.
