### ISSUE TITLE
Odd import error

### ISSUE THREAD

**Issue by stonier** [asmodehn/pyros#57]
The code here looks ok, but it triggers a failed import when running (`gocart_sim.launch`):

```
[2016-01-29 15:55:35,120: WARNING/MainProcess] Error: could not import RoconInterface - disabling. No module named roconinterface.rocon_interface
WARNING:root:Error: could not import RoconInterface - disabling. No module named roconinterface.rocon_interface
```

**Comment by asmodehn** [comment]
This is an internal warning of pyros.
Since I haven't kept all the rocon things uptodate, the rocon part of pyros (rapp + interactions handling) fails and disables itself.

I have been thinking about dropping it. Gopher is not using it anyway.
And it could be done in another project, using pyros underneath.

**Comment by asmodehn** [comment]
Planning to drop rocon support https://github.com/asmodehn/pyros/issues/61
